import type { FlowerProduct } from '@/types'

export const STATIC_FLOWERS: FlowerProduct[] = [
  // --- Помпонові ---
  {
    id: 'sf-01', name: 'Anastasia White', slug: 'anastasia-white', category: 'chrysanthemum',
    variety: 'Помпонова', short_description: 'Класична помпонова хризантема з сніжно-білими суцвіттями. Один із найпопулярніших сортів для зрізу.',
    full_description: 'Компактні кулясті суцвіття діаметром 4–6 см. Довга ваза — до 14 днів. Ідеальна для букетів і весільних композицій.',
    price_uah: 75, color: 'Білий', bloom_season: 'Вересень–Жовтень', height_cm: 65,
    lighting: 'Сонце', packaging_note: 'Укорінений живець або паросток', display_order: 1,
    is_featured: true, status: 'available', image_url: null, image_alt: 'Anastasia White — біла помпонова хризантема', youtube_video_url: null,
  },
  {
    id: 'sf-02', name: 'Малиновий захід', slug: 'malynovyi-zakhid', category: 'chrysanthemum',
    variety: 'Помпонова', short_description: 'Яскраво-малинові кульки з легким перламутровим відливом. Сорт стійкий до осінніх дощів.',
    full_description: 'Висота куща до 60 см, рясне цвітіння. Відмінно підходить для вазонного вирощування і клумб.',
    price_uah: 80, color: 'Малиновий', bloom_season: 'Жовтень', height_cm: 60,
    lighting: 'Сонце', packaging_note: 'Укорінений живець', display_order: 2,
    is_featured: true, status: 'available', image_url: null, image_alt: 'Малиновий захід — малинова помпонова хризантема', youtube_video_url: null,
  },
  {
    id: 'sf-03', name: 'Золота осінь', slug: 'zolota-osin', category: 'chrysanthemum',
    variety: 'Помпонова', short_description: 'Соковито-жовті суцвіття на міцних стеблах. Класика осіннього саду.',
    full_description: null, price_uah: 70, color: 'Жовтий', bloom_season: 'Вересень–Жовтень',
    height_cm: 55, lighting: 'Сонце', packaging_note: null, display_order: 3,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-04', name: 'Сніжинка', slug: 'snezhynka', category: 'chrysanthemum',
    variety: 'Помпонова', short_description: 'Дрібні білі суцвіття з кремовим центром. Ніжний, «хмарний» вигляд.',
    full_description: null, price_uah: 70, color: 'Білий/Кремовий', bloom_season: 'Жовтень',
    height_cm: 50, lighting: 'Сонце', packaging_note: null, display_order: 4,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-05', name: 'Бронзова', slug: 'bronzova', category: 'chrysanthemum',
    variety: 'Помпонова', short_description: 'Мідно-бронзовий відтінок із переходом у теракоту. Модна осіння палітра.',
    full_description: null, price_uah: 75, color: 'Бронзовий', bloom_season: 'Жовтень',
    height_cm: 60, lighting: 'Сонце', packaging_note: null, display_order: 5,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-06', name: 'Ліловий сон', slug: 'lilovyi-son', category: 'chrysanthemum',
    variety: 'Помпонова', short_description: 'Пастельно-ліловий колір, що підсилюється на прохолоді. Чарівна осіння квітка.',
    full_description: null, price_uah: 80, color: 'Ліловий', bloom_season: 'Жовтень',
    height_cm: 55, lighting: 'Сонце', packaging_note: null, display_order: 6,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-07', name: 'Рожева хмара', slug: 'rozheva-khmara', category: 'chrysanthemum',
    variety: 'Помпонова', short_description: 'Ніжно-рожеві кульки, дуже рясне цвітіння. Чудово виглядає в масових посадках.',
    full_description: null, price_uah: 75, color: 'Рожевий', bloom_season: 'Вересень–Жовтень',
    height_cm: 55, lighting: 'Сонце', packaging_note: null, display_order: 7,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-08', name: 'Оранжева іскра', slug: 'oranzeva-iskra', category: 'chrysanthemum',
    variety: 'Помпонова', short_description: 'Яскраво-помаранчеві суцвіття — справжня окраса осіннього саду.',
    full_description: null, price_uah: 70, color: 'Помаранчевий', bloom_season: 'Жовтень',
    height_cm: 50, lighting: 'Сонце', packaging_note: null, display_order: 8,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-09', name: 'Темно-червона', slug: 'temno-chervona', category: 'chrysanthemum',
    variety: 'Помпонова', short_description: 'Насичено-бордовий колір із оксамитовою текстурою пелюсток.',
    full_description: null, price_uah: 80, color: 'Бордо/Темно-червоний', bloom_season: 'Жовтень',
    height_cm: 60, lighting: 'Сонце', packaging_note: null, display_order: 9,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },

  // --- Кущові ---
  {
    id: 'sf-10', name: 'Балтика Жовта', slug: 'baltyka-zhovta', category: 'chrysanthemum',
    variety: 'Кущова', short_description: 'Кущова хризантема з яскраво-жовтими суцвіттями середнього розміру. Зимостійка.',
    full_description: 'Кущ розгалужений, висотою до 70 см. Суцвіття 6–8 см, щільні, довго тримаються у вазі.',
    price_uah: 85, color: 'Жовтий', bloom_season: 'Вересень–Жовтень', height_cm: 70,
    lighting: 'Сонце', packaging_note: 'Укорінений живець', display_order: 10,
    is_featured: true, status: 'available', image_url: null, image_alt: 'Балтика Жовта — кущова хризантема', youtube_video_url: null,
  },
  {
    id: 'sf-11', name: 'Балтика Біла', slug: 'baltyka-bila', category: 'chrysanthemum',
    variety: 'Кущова', short_description: 'Білосніжна кущова хризантема — класика для зрізу та клумб.',
    full_description: null, price_uah: 85, color: 'Білий', bloom_season: 'Вересень–Жовтень',
    height_cm: 70, lighting: 'Сонце', packaging_note: null, display_order: 11,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-12', name: 'Балтика Рожева', slug: 'baltyka-rozheva', category: 'chrysanthemum',
    variety: 'Кущова', short_description: 'Ніжно-рожеві суцвіття з кремовим центром. Популярна в осінніх букетах.',
    full_description: null, price_uah: 85, color: 'Рожевий', bloom_season: 'Вересень–Жовтень',
    height_cm: 70, lighting: 'Сонце', packaging_note: null, display_order: 12,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-13', name: 'Кармен', slug: 'karmen', category: 'chrysanthemum',
    variety: 'Кущова', short_description: 'Малинові суцвіття з темнішим центром. Назва говорить сама за себе — пристрасна й виразна.',
    full_description: null, price_uah: 90, color: 'Малиново-бордовий', bloom_season: 'Жовтень',
    height_cm: 65, lighting: 'Сонце', packaging_note: null, display_order: 13,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-14', name: 'Зоряна ніч', slug: 'zoriana-nich', category: 'chrysanthemum',
    variety: 'Кущова', short_description: 'Темно-фіолетові суцвіття зі срібним відтінком. Ефектна квітка для контрастних композицій.',
    full_description: null, price_uah: 90, color: 'Фіолетовий', bloom_season: 'Жовтень',
    height_cm: 60, lighting: 'Сонце', packaging_note: null, display_order: 14,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-15', name: 'Сонячний промінь', slug: 'soniachnyi-promin', category: 'chrysanthemum',
    variety: 'Кущова', short_description: 'Яскраво-жовтогарячі суцвіття, стійкість до дощу та вітру. Незамінна на клумбі.',
    full_description: null, price_uah: 80, color: 'Жовтогарячий', bloom_season: 'Вересень–Жовтень',
    height_cm: 65, lighting: 'Сонце', packaging_note: null, display_order: 15,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-16', name: 'Персикова', slug: 'persykova', category: 'chrysanthemum',
    variety: 'Кущова', short_description: 'Персиково-абрикосовий відтінок, що рідко зустрічається у кущових хризантем.',
    full_description: null, price_uah: 90, color: 'Персиковий', bloom_season: 'Жовтень',
    height_cm: 60, lighting: 'Сонце', packaging_note: null, display_order: 16,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-17', name: 'Зелений чай', slug: 'zelenyi-chai', category: 'chrysanthemum',
    variety: 'Кущова', short_description: 'Незвичайна хризантема з салатово-зеленими суцвіттями. Оригінально виглядає в букеті.',
    full_description: null, price_uah: 95, color: 'Зелений', bloom_season: 'Жовтень',
    height_cm: 65, lighting: 'Сонце', packaging_note: null, display_order: 17,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-18', name: 'Крем-брюле', slug: 'krem-briule', category: 'chrysanthemum',
    variety: 'Кущова', short_description: 'Кремово-вершковий тон із легким рожевим підтоном. Витончена й ніжна.',
    full_description: null, price_uah: 85, color: 'Кремовий', bloom_season: 'Вересень–Жовтень',
    height_cm: 60, lighting: 'Сонце', packaging_note: null, display_order: 18,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-19', name: 'Теракота', slug: 'terakota', category: 'chrysanthemum',
    variety: 'Кущова', short_description: 'Земляний теракотово-іржавий колір — актуальний тренд флористики.',
    full_description: null, price_uah: 90, color: 'Теракота', bloom_season: 'Жовтень',
    height_cm: 65, lighting: 'Сонце', packaging_note: null, display_order: 19,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },

  // --- Великоквіткові ---
  {
    id: 'sf-20', name: 'Біла перлина', slug: 'bila-perlyna', category: 'chrysanthemum',
    variety: 'Великоквіткова', short_description: 'Одностеблова хризантема з великою квіткою діаметром 16–20 см. Ідеальна для показових букетів.',
    full_description: 'Класична великоквіткова хризантема для зрізу. Утворює одну велику квітку на стеблі. Потребує пасинкування.',
    price_uah: 110, color: 'Білий', bloom_season: 'Жовтень–Листопад', height_cm: 90,
    lighting: 'Сонце', packaging_note: 'Укорінений живець', display_order: 20,
    is_featured: true, status: 'available', image_url: null, image_alt: 'Біла перлина — великоквіткова хризантема', youtube_video_url: null,
  },
  {
    id: 'sf-21', name: 'Золотий лев', slug: 'zolotyi-lev', category: 'chrysanthemum',
    variety: 'Великоквіткова', short_description: 'Золотисто-жовта великоквіткова хризантема з щільними пелюстками. Виставковий сорт.',
    full_description: null, price_uah: 120, color: 'Золотисто-жовтий', bloom_season: 'Жовтень–Листопад',
    height_cm: 95, lighting: 'Сонце', packaging_note: null, display_order: 21,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-22', name: 'Рожевий захід', slug: 'rozhevyi-zakhid', category: 'chrysanthemum',
    variety: 'Великоквіткова', short_description: 'Ніжно-рожева квітка з інтенсивнішим кольором у центрі. Виглядає розкішно.',
    full_description: null, price_uah: 115, color: 'Рожевий', bloom_season: 'Жовтень',
    height_cm: 90, lighting: 'Сонце', packaging_note: null, display_order: 22,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-23', name: 'Бургундський оксамит', slug: 'burhunskyi-oksemyt', category: 'chrysanthemum',
    variety: 'Великоквіткова', short_description: 'Глибокий бургундський колір із оксамитовою текстурою. Розкіш для осіннього букету.',
    full_description: null, price_uah: 125, color: 'Бургундський', bloom_season: 'Жовтень–Листопад',
    height_cm: 95, lighting: 'Сонце', packaging_note: null, display_order: 23,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-24', name: 'Помаранч', slug: 'pomaranch', category: 'chrysanthemum',
    variety: 'Великоквіткова', short_description: 'Яскраво-помаранчева квітка великого розміру. Привертає увагу здалеку.',
    full_description: null, price_uah: 110, color: 'Помаранчевий', bloom_season: 'Жовтень',
    height_cm: 85, lighting: 'Сонце', packaging_note: null, display_order: 24,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-25', name: 'Кремова регіна', slug: 'kremova-rehina', category: 'chrysanthemum',
    variety: 'Великоквіткова', short_description: 'Кремово-білий колір із ледь помітним лимонним відтінком у центрі.',
    full_description: null, price_uah: 115, color: 'Кремовий', bloom_season: 'Жовтень–Листопад',
    height_cm: 90, lighting: 'Сонце', packaging_note: null, display_order: 25,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-26', name: 'Сріблясте сяйво', slug: 'sriblaste-siaivo', category: 'chrysanthemum',
    variety: 'Великоквіткова', short_description: 'Сріблясто-бузковий відтінок з виразним виставковим виглядом.',
    full_description: null, price_uah: 130, color: 'Сріблясто-бузковий', bloom_season: 'Листопад',
    height_cm: 100, lighting: 'Сонце', packaging_note: null, display_order: 26,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },

  // --- Дрібноквіткові ---
  {
    id: 'sf-27', name: 'Біла зірочка', slug: 'bila-zirochka', category: 'chrysanthemum',
    variety: 'Дрібноквіткова', short_description: 'Безліч дрібних білих ромашкоподібних квіток на одному кущі. Витончено й легко.',
    full_description: 'Утворює хмарку з квіток діаметром 2–3 см. Чудово виглядає в масових посадках і живоплотах.',
    price_uah: 65, color: 'Білий', bloom_season: 'Вересень–Жовтень', height_cm: 50,
    lighting: 'Сонце', packaging_note: null, display_order: 27,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-28', name: 'Рожевий дощ', slug: 'rozhevyi-doshch', category: 'chrysanthemum',
    variety: 'Дрібноквіткова', short_description: 'Ніжні рожеві суцвіття розміром з монетку. Рясне довготривале цвітіння.',
    full_description: null, price_uah: 65, color: 'Рожевий', bloom_season: 'Вересень–Жовтень',
    height_cm: 45, lighting: 'Сонце', packaging_note: null, display_order: 28,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-29', name: 'Медова крапля', slug: 'medova-kraplia', category: 'chrysanthemum',
    variety: 'Дрібноквіткова', short_description: 'Медово-жовті дрібні квітки. Невибаглива у догляді, стійка до морозів.',
    full_description: null, price_uah: 65, color: 'Медово-жовтий', bloom_season: 'Жовтень',
    height_cm: 45, lighting: 'Сонце', packaging_note: null, display_order: 29,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-30', name: 'Лавандовий туман', slug: 'lavandovyi-tuman', category: 'chrysanthemum',
    variety: 'Дрібноквіткова', short_description: 'Лавандові дрібні квітки зі срібним відблиском. Незвична кольорова гама.',
    full_description: null, price_uah: 70, color: 'Лавандовий', bloom_season: 'Жовтень',
    height_cm: 50, lighting: 'Сонце', packaging_note: null, display_order: 30,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-31', name: 'Помаранчева феєрія', slug: 'pomarancheva-feieriia', category: 'chrysanthemum',
    variety: 'Дрібноквіткова', short_description: 'Соковито-помаранчеві дрібні квіти — яскрава пляма на клумбі в жовтні.',
    full_description: null, price_uah: 65, color: 'Помаранчевий', bloom_season: 'Жовтень',
    height_cm: 45, lighting: 'Сонце', packaging_note: null, display_order: 31,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },

  // --- Компактні ---
  {
    id: 'sf-32', name: 'Мінарет Білий', slug: 'minaret-bilyi', category: 'chrysanthemum',
    variety: 'Компактна', short_description: 'Компактний кущ висотою до 35 см з рясними білими суцвіттями. Ідеальна для вазонів.',
    full_description: 'Не потребує пасинкування. Відмінно розростається в горщиках і контейнерах на балконі.',
    price_uah: 75, color: 'Білий', bloom_season: 'Жовтень', height_cm: 35,
    lighting: 'Сонце', packaging_note: 'Укорінений живець', display_order: 32,
    is_featured: false, status: 'available', image_url: null, image_alt: 'Мінарет Білий — компактна хризантема', youtube_video_url: null,
  },
  {
    id: 'sf-33', name: 'Мінарет Рожевий', slug: 'minaret-rozhevyi', category: 'chrysanthemum',
    variety: 'Компактна', short_description: 'Рожева компактна хризантема — маленька, але дуже рясноцвіта.',
    full_description: null, price_uah: 75, color: 'Рожевий', bloom_season: 'Жовтень',
    height_cm: 35, lighting: 'Сонце', packaging_note: null, display_order: 33,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-34', name: 'Мінарет Жовтий', slug: 'minaret-zhovtyi', category: 'chrysanthemum',
    variety: 'Компактна', short_description: 'Жовта компактна форма. Невибаглива, морозостійка, підходить для новачків.',
    full_description: null, price_uah: 70, color: 'Жовтий', bloom_season: 'Жовтень',
    height_cm: 30, lighting: 'Сонце', packaging_note: null, display_order: 34,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-35', name: 'Балкон Лайм', slug: 'balkon-laim', category: 'chrysanthemum',
    variety: 'Компактна', short_description: 'Салатово-лаймовий колір, компактний кущ — хіт для балконних вазонів.',
    full_description: null, price_uah: 80, color: 'Салатовий/Лайм', bloom_season: 'Жовтень',
    height_cm: 30, lighting: 'Сонце', packaging_note: null, display_order: 35,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },

  // --- Анемонові ---
  {
    id: 'sf-36', name: 'Анемон Рожевий', slug: 'anemon-rozhevyi', category: 'chrysanthemum',
    variety: 'Анемонова', short_description: 'Характерна будова квітки: плоскі зовнішні пелюстки й опукле центральне вічко. Унікально.',
    full_description: 'Анемоновидна хризантема виглядає як два квіти в одному. Пухнастий центр гармоніює з плоскими крайовими пелюстками.',
    price_uah: 90, color: 'Рожевий', bloom_season: 'Вересень–Жовтень', height_cm: 60,
    lighting: 'Сонце', packaging_note: null, display_order: 36,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-37', name: 'Анемон Білий', slug: 'anemon-bilyi', category: 'chrysanthemum',
    variety: 'Анемонова', short_description: 'Білі пелюстки та жовто-зелений центр. Нагадує велику ромашку з характером.',
    full_description: null, price_uah: 90, color: 'Білий/Жовтий центр', bloom_season: 'Жовтень',
    height_cm: 55, lighting: 'Сонце', packaging_note: null, display_order: 37,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-38', name: 'Анемон Бронза', slug: 'anemon-bronza', category: 'chrysanthemum',
    variety: 'Анемонова', short_description: 'Бронзово-помаранчеві крайові пелюстки та густий рудий центр. Незвична осіння краса.',
    full_description: null, price_uah: 95, color: 'Бронзово-помаранчевий', bloom_season: 'Жовтень',
    height_cm: 60, lighting: 'Сонце', packaging_note: null, display_order: 38,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },

  // --- Павукоподібні ---
  {
    id: 'sf-39', name: 'Павук Жовтий', slug: 'pavuk-zhovtyi', category: 'chrysanthemum',
    variety: 'Павукоподібна', short_description: 'Довгі закручені пелюстки золотисто-жовтого кольору. Екзотичний вигляд, яскравий акцент.',
    full_description: 'Spider (павукоподібна) хризантема з трубчастими звивистими пелюстками 10–15 см. Діаметр квітки до 25 см.',
    price_uah: 120, color: 'Золотисто-жовтий', bloom_season: 'Жовтень–Листопад', height_cm: 100,
    lighting: 'Сонце', packaging_note: 'Укорінений живець', display_order: 39,
    is_featured: true, status: 'available', image_url: null, image_alt: 'Павук Жовтий — павукоподібна хризантема', youtube_video_url: null,
  },
  {
    id: 'sf-40', name: 'Павук Білий', slug: 'pavuk-bilyi', category: 'chrysanthemum',
    variety: 'Павукоподібна', short_description: 'Крученопелюсткова хризантема в молочно-білому кольорі. Ефектна у флористиці.',
    full_description: null, price_uah: 120, color: 'Молочно-білий', bloom_season: 'Жовтень–Листопад',
    height_cm: 95, lighting: 'Сонце', packaging_note: null, display_order: 40,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-41', name: 'Павук Ліловий', slug: 'pavuk-lilovyi', category: 'chrysanthemum',
    variety: 'Павукоподібна', short_description: 'Ліловий spider — рідкісний та ефектний. Виставковий сорт.',
    full_description: null, price_uah: 130, color: 'Ліловий', bloom_season: 'Листопад',
    height_cm: 100, lighting: 'Сонце', packaging_note: null, display_order: 41,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },

  // --- Двоколірні ---
  {
    id: 'sf-42', name: 'Ягуар', slug: 'yahuar', category: 'chrysanthemum',
    variety: 'Помпонова', short_description: 'Жовті пелюстки з червоно-бронзовими кінчиками. Кожна квітка виглядає унікально.',
    full_description: null, price_uah: 85, color: 'Жовтий/Бронзовий', bloom_season: 'Жовтень',
    height_cm: 60, lighting: 'Сонце', packaging_note: null, display_order: 42,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-43', name: 'Хамелеон', slug: 'khameleon', category: 'chrysanthemum',
    variety: 'Кущова', short_description: 'Колір змінюється з рожевого до кораловогоо залежно від температури. Унікальний сорт.',
    full_description: null, price_uah: 95, color: 'Рожево-кораловий', bloom_season: 'Жовтень',
    height_cm: 65, lighting: 'Сонце', packaging_note: null, display_order: 43,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-44', name: 'Фламінго', slug: 'flaminho', category: 'chrysanthemum',
    variety: 'Великоквіткова', short_description: 'Рожево-помаранчевий градієнт від центру до кінців пелюсток. Ефектна для виставок.',
    full_description: null, price_uah: 125, color: 'Рожево-помаранчевий', bloom_season: 'Жовтень–Листопад',
    height_cm: 90, lighting: 'Сонце', packaging_note: null, display_order: 44,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-45', name: 'Леопард', slug: 'leopard', category: 'chrysanthemum',
    variety: 'Помпонова', short_description: 'Білі пелюстки з рожево-малиновим штрихуванням. Незвичайний, «плямистий» ефект.',
    full_description: null, price_uah: 85, color: 'Білий/Рожевий', bloom_season: 'Жовтень',
    height_cm: 55, lighting: 'Сонце', packaging_note: null, display_order: 45,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },

  // --- Пізні ---
  {
    id: 'sf-46', name: 'Сибірська красуня', slug: 'sybirska-krasunіa', category: 'chrysanthemum',
    variety: 'Кущова', short_description: 'Надзвичайно морозостійкий сорт — цвіте навіть після легких морозів. Для відкритого ґрунту.',
    full_description: null, price_uah: 90, color: 'Рожево-ліловий', bloom_season: 'Жовтень–Листопад',
    height_cm: 70, lighting: 'Сонце', packaging_note: null, display_order: 46,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-47', name: 'Зимовий сад', slug: 'zymovyi-sad', category: 'chrysanthemum',
    variety: 'Помпонова', short_description: 'Пізньоцвітний сорт — найдовше залишається в саду. Стійкий до заморозків до -7°C.',
    full_description: null, price_uah: 80, color: 'Білий/Кремовий', bloom_season: 'Листопад',
    height_cm: 55, lighting: 'Сонце', packaging_note: null, display_order: 47,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-48', name: 'Пізня осінь', slug: 'piznia-osin', category: 'chrysanthemum',
    variety: 'Кущова', short_description: 'Насичено-бордові суцвіття в кінці сезону. Останній барвистий акорд саду.',
    full_description: null, price_uah: 85, color: 'Бордо', bloom_season: 'Листопад',
    height_cm: 65, lighting: 'Сонце', packaging_note: null, display_order: 48,
    is_featured: false, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },

  // --- Ексклюзивні ---
  {
    id: 'sf-49', name: 'Шоколадна', slug: 'shokoladna', category: 'chrysanthemum',
    variety: 'Помпонова', short_description: 'Темно-шоколадний, майже коричневий відтінок. Дуже рідкісна й затребувана флористами.',
    full_description: null, price_uah: 100, color: 'Шоколадний/Коричневий', bloom_season: 'Жовтень',
    height_cm: 60, lighting: 'Сонце', packaging_note: null, display_order: 49,
    is_featured: true, status: 'available', image_url: null, image_alt: null, youtube_video_url: null,
  },
  {
    id: 'sf-50', name: 'Голуба мрія', slug: 'holuba-mriia', category: 'chrysanthemum',
    variety: 'Великоквіткова', short_description: 'Бузково-блакитний відтінок — одна з найрідкісніших барв у хризантем. Колекційний сорт.',
    full_description: 'Дуже рідкісна забарвлення для хризантеми. Квітка утворює один великий бутон діаметром до 18 см. Використовується на виставках.',
    price_uah: 130, color: 'Бузково-блакитний', bloom_season: 'Жовтень–Листопад',
    height_cm: 95, lighting: 'Сонце', packaging_note: 'Укорінений живець (обмежена кількість)', display_order: 50,
    is_featured: true, status: 'available', image_url: null, image_alt: 'Голуба мрія — рідкісна велика хризантема', youtube_video_url: null,
  },
]
