export const LAUNCH_PHONE = '+380967657772'
export const LAUNCH_PHONE_SECONDARY = '+380934665801'
export const LAUNCH_YOUTUBE_URL = 'https://www.youtube.com/@dacha_tv'
export const LAUNCH_YOUTUBE_VIDEO_ID = 'Qwmi6Igjp4I'
export const LAUNCH_INSTAGRAM_URL = 'https://instagram.com/dachatv.store'
export const LAUNCH_FACEBOOK_URL = 'https://facebook.com/kyzmenko.sergej'
export const LAUNCH_FACEBOOK_URL_2 = 'https://facebook.com/profile.php?id=100093442074407'
export const LAUNCH_TIKTOK_URL = 'https://tiktok.com/@vladkuzmenkosxy'
export const LAUNCH_ADDRESS = 'Коротич, Пісочинська ОТГ, Харківська область, Україна'
export const LAUNCH_LOGO_PATH = '/images/dacha-tv/logo.png'
export const LAUNCH_LOGO_SQUARE_PATH = '/images/dacha-tv/logo-square.png'
