import type { HoneyProduct } from '@/types'

export const STATIC_HONEY: HoneyProduct[] = [
  {
    id: 'static-1', slug: 'acacia-honey', name: 'Акацієвий мед', variety: 'Акація',
    description: null,
    short_description: 'Ніжний, світлий мед із делікатним ароматом та повільною кристалізацією.',
    full_description: "Акацієвий мед цінується за м'який смак, світлий відтінок і легкий квітковий аромат. Це один із найбільш делікатних сортів, який довше залишається рідким і добре підходить для щоденного вживання.",
    aroma_notes: 'Легкий квітковий, ненав\'язливий',
    taste_notes: 'Ніжний, злегка вершковий, без різких відтінків',
    color_note: 'Дуже світлий, майже прозорий',
    crystallization_note: 'Кристалізується дуже повільно — іноді залишається рідким до року і довше.',
    recommended_use: 'Щоденне вживання, чай, дитяче харчування, подарунки.',
    packaging_note: '1 л. Пластикова та скляна банка.',
    packaging: ['1 л пластик', '1 л скло'],
    price_plastic_uah: 500, price_glass_uah: 500,
    is_featured: true, status: 'available', display_order: 1,
    image_url: '/images/dacha-tv/honey/acacia-honey-01.jpg',
    image_alt: 'Акацієвий мед Dacha TV', youtube_video_link: null,
  },
  {
    id: 'static-2', slug: 'linden-honey', name: 'Липовий мед', variety: 'Липа',
    description: null,
    short_description: 'Класичний запашний мед із виразним ароматом липового цвіту.',
    full_description: "Липовий мед має насичений аромат, характерний трав'янисто-квітковий профіль і традиційно вважається одним із найулюбленіших сортів. Добре підходить до чаю та для домашнього запасу.",
    aroma_notes: "Насичений, квітково-трав'янистий",
    taste_notes: 'Насичений, з легкою приємною гіркуватістю',
    color_note: 'Від світло-жовтого до золотисто-янтарного',
    crystallization_note: 'Кристалізується за 2–3 місяці. Кристали середнього розміру.',
    recommended_use: 'Чай, щоденне вживання, підтримка імунітету в сезон застуд.',
    packaging_note: '1 л. Пластикова та скляна банка.',
    packaging: ['1 л пластик', '1 л скло'],
    price_plastic_uah: 500, price_glass_uah: 500,
    is_featured: true, status: 'available', display_order: 2,
    image_url: '/images/dacha-tv/honey/linden-honey-01.jpg',
    image_alt: 'Липовий мед Dacha TV', youtube_video_link: null,
  },
  {
    id: 'static-3', slug: 'sunflower-honey', name: 'Соняшниковий мед', variety: 'Сонях',
    description: null,
    short_description: 'Насичений золотистий мед із виразним смаком і швидшою кристалізацією.',
    full_description: 'Соняшниковий мед має яскравий колір, щільнішу текстуру та характерний солодкий смак. Це популярний повсякденний сорт, добре знайомий багатьом покупцям.',
    aroma_notes: 'Характерний, теплий, медово-квітковий',
    taste_notes: 'Насичений, жирний, виразний соняшниковий',
    color_note: 'Яскраво-золотистий, насичений',
    crystallization_note: 'Кристалізується дуже швидко — за 2–4 тижні після відкачки. Кристали дрібні й тверді.',
    recommended_use: 'Намазати на хліб, додати в кашу. Підходить для тривалого зберігання.',
    packaging_note: '1 л. Пластикова та скляна банка.',
    packaging: ['1 л пластик', '1 л скло'],
    price_plastic_uah: 500, price_glass_uah: 500,
    is_featured: true, status: 'available', display_order: 3,
    image_url: '/images/dacha-tv/honey/sunflower-honey-01.jpg',
    image_alt: 'Соняшниковий мед Dacha TV', youtube_video_link: null,
  },
  {
    id: 'static-4', slug: 'wildflower-honey', name: "Мед різнотрав'я", variety: "Різнотрав'я",
    description: null,
    short_description: "Багатий природний смак із поєднанням нектару різних польових рослин.",
    full_description: "Мед різнотрав'я збирається з багатьох літніх квітів, тому має багатший і глибший смаковий профіль. Кожна партія може мати свій характер залежно від сезону та медоносів.",
    aroma_notes: 'Складний, багатошаровий, природний',
    taste_notes: 'Глибокий, зі змінним характером залежно від партії',
    color_note: 'Від золотистого до янтарного',
    crystallization_note: "Кристалізується за 1–3 місяці залежно від складу нектару.",
    recommended_use: "Універсальний. Щоденне вживання, випічка, чай.",
    packaging_note: '1 л. Пластикова та скляна банка.',
    packaging: ['1 л пластик', '1 л скло'],
    price_plastic_uah: 500, price_glass_uah: 500,
    is_featured: true, status: 'available', display_order: 4,
    image_url: '/images/dacha-tv/honey/wildflower-honey-01.jpg',
    image_alt: "Мед різнотрав'я Dacha TV", youtube_video_link: null,
  },
  {
    id: 'static-5', slug: 'orchard-honey', name: 'Садовий мед', variety: 'Сади',
    description: null,
    short_description: "Ароматний мед із м'яким фруктово-квітковим характером.",
    full_description: "Садовий мед формується з весняного цвіту плодових дерев та інших садових медоносів. Він має приємний квітковий аромат і м'який смак, який добре підходить для сімейного столу.",
    aroma_notes: "Квітково-фруктовий, весняний",
    taste_notes: "М'який, ніжний, з фруктовими нотками",
    color_note: 'Світло-жовтий, прозорий',
    crystallization_note: "Кристалізується за 2–3 місяці. Кристали м'які та дрібні.",
    recommended_use: 'Чай, десерти, сир. Ідеально для сімейного столу.',
    packaging_note: '1 л. Пластикова та скляна банка.',
    packaging: ['1 л пластик', '1 л скло'],
    price_plastic_uah: 500, price_glass_uah: 500,
    is_featured: true, status: 'available', display_order: 5,
    image_url: '/images/dacha-tv/honey/orchard-honey-01.jpg',
    image_alt: 'Садовий мед Dacha TV', youtube_video_link: null,
  },
  {
    id: 'static-6', slug: 'forest-honey', name: 'Лісовий мед', variety: 'Ліс',
    description: null,
    short_description: 'Глибший, більш насичений смак із виразним природним характером.',
    full_description: "Лісовий мед зазвичай має темніший відтінок, більш глибокий аромат і насичений смак. Це добрий вибір для тих, хто любить більш яскравий медовий профіль.",
    aroma_notes: 'Смолистий, деревний, складний',
    taste_notes: 'Темний, насичений, з мінеральними нотками',
    color_note: 'Темно-янтарний, коричнюватий',
    crystallization_note: "Кристалізується повільно. Може зберігатися рідким тривалий час.",
    recommended_use: "Для цінителів — самостійно або до страв із м'ясом та сирами.",
    packaging_note: '1 л. Пластикова та скляна банка.',
    packaging: ['1 л пластик', '1 л скло'],
    price_plastic_uah: 500, price_glass_uah: 500,
    is_featured: true, status: 'available', display_order: 6,
    image_url: '/images/dacha-tv/honey/forest-honey-01.jpg',
    image_alt: 'Лісовий мед Dacha TV', youtube_video_link: null,
  },
]

export const STATIC_HONEY_BY_SLUG: Record<string, HoneyProduct> = Object.fromEntries(
  STATIC_HONEY.map((p) => [p.slug, p])
)

export const STATIC_HONEY_SLUGS = STATIC_HONEY.map((p) => p.slug)
