import type { ApiaryProduct, BeekeeperProduct } from '@/types'

export const STATIC_APIARY: ApiaryProduct[] = [
  {
    id: 'static-apiary-2',
    name: 'Квітковий пилок',
    slug: 'flower-pollen',
    description: 'Натуральний квітковий пилок зібраний на нашій пасіці.',
    short_description: 'Свіжий квітковий пилок — джерело вітамінів, амінокислот та мікроелементів.',
    full_description: 'Квітковий пилок містить понад 250 біологічно активних речовин. Рекомендується для підтримки імунітету та загального оздоровлення організму.',
    composition: 'Натуральний квітковий пилок',
    usage_notes: 'Вживати по 1–2 чайні ложки на день, запиваючи водою або розчиняючи в меду.',
    storage_info: 'Зберігати в холодильнику або морозильній камері.',
    packaging_note: '50 г, 100 г',
    packaging: ['50 г', '100 г'],
    price_uah: 180,
    weight_g: 100,
    is_featured: false,
    status: 'available',
    display_order: 1,
    image_url: null,
    image_alt: 'Квітковий пилок Dacha TV',
    youtube_video_url: null,
    gallery_images: null,
  },
  {
    id: 'static-apiary-3',
    name: 'Прополіс',
    slug: 'propolis',
    description: 'Натуральний прополіс із нашої пасіки.',
    short_description: 'Натуральний прополіс — природний антисептик та імуностимулятор.',
    full_description: 'Прополіс має сильні антибактеріальні та антивірусні властивості. Використовується як природний антисептик і для підтримки імунної системи.',
    composition: null,
    usage_notes: 'Вживати у вигляді настоянки або додавати до меду.',
    storage_info: 'Зберігати в прохолодному темному місці.',
    packaging_note: '20 г',
    packaging: ['20 г'],
    price_uah: 120,
    weight_g: 20,
    is_featured: false,
    status: 'available',
    display_order: 2,
    image_url: null,
    image_alt: 'Прополіс Dacha TV',
    youtube_video_url: null,
    gallery_images: null,
  },
  {
    id: 'static-apiary-4',
    name: 'Горіхи в меду',
    slug: 'nuts-in-honey',
    description: 'Суміш волоських горіхів і мигдалю в натуральному меду.',
    short_description: 'Волоські горіхи та мигдаль у натуральному меді — корисне та смачне ласощі.',
    full_description: 'Суміш відборних горіхів у натуральному меді. Енергетичний та поживний продукт, що поєднує корисні властивості меду та горіхів.',
    composition: 'Натуральний мед, волоські горіхи, мигдаль',
    usage_notes: 'Вживати по 1–2 столові ложки на день як самостійний десерт або з хлібом.',
    storage_info: 'Зберігати в прохолодному темному місці. Термін придатності — 12 місяців.',
    packaging_note: '200 г, 500 г',
    packaging: ['200 г', '500 г'],
    price_uah: 230,
    weight_g: 200,
    is_featured: false,
    status: 'available',
    display_order: 3,
    image_url: null,
    image_alt: 'Горіхи в меду Dacha TV',
    youtube_video_url: null,
    gallery_images: null,
  },
]

export const STATIC_APIARY_BY_SLUG: Record<string, ApiaryProduct> = Object.fromEntries(
  STATIC_APIARY.map((p) => [p.slug, p])
)

export const STATIC_APIARY_SLUGS = STATIC_APIARY.map((p) => p.slug)

export const STATIC_BEEKEEPER: BeekeeperProduct[] = [
  {
    id: 'static-beekeeper-1',
    name: 'Бджолопакети',
    slug: 'bee-packages',
    product_type: 'bee_packages',
    description: 'Бджолопакети порід Buckfast та Карніка. Спокійні, продуктивні породи. Доступні з квітня по червень.',
    full_description: null,
    breeds: ['Buckfast', 'Карніка'],
    season_note: 'Доступні з квітня по червень',
    price_uah: null,
    price_note: null,
    display_order: 1,
    status: 'available',
    is_featured: false,
    image_url: null,
    image_alt: null,
    youtube_video_url: null,
    gallery_images: null,
  },
  {
    id: 'static-beekeeper-2',
    name: 'Бджолосімї',
    slug: 'bee-colonies',
    product_type: 'bee_colonies',
    description: 'Повноцінні бджолосімї у вуликах. Підходять для початківців і досвідчених пасічників.',
    full_description: null,
    breeds: ['Buckfast', 'Карніка'],
    season_note: 'Доступні з квітня по серпень',
    price_uah: null,
    price_note: null,
    display_order: 2,
    status: 'available',
    is_featured: false,
    image_url: null,
    image_alt: null,
    youtube_video_url: null,
    gallery_images: null,
  },
  {
    id: 'static-beekeeper-3',
    name: 'Порожні вулики',
    slug: 'empty-hives',
    product_type: 'empty_hives',
    description: 'Порожні вулики для самостійного заселення. Уточнюйте наявність та конструкцію.',
    full_description: null,
    breeds: null,
    season_note: null,
    price_uah: null,
    price_note: null,
    display_order: 3,
    status: 'available',
    is_featured: false,
    image_url: null,
    image_alt: null,
    youtube_video_url: null,
    gallery_images: null,
  },
  {
    id: 'static-beekeeper-4',
    name: 'Приманка для роїв',
    slug: 'swarm-lure',
    product_type: 'apiary_supply',
    description: 'Приманка для роїв використовується в сезон роїння для підвищення шансів заселення пастки або підготовленого вулика. Зручний формат банки дозволяє легко використовувати продукт у практичній роботі на пасіці.',
    full_description: null,
    breeds: null,
    season_note: 'Сезон роїння: квітень–липень',
    price_uah: null,
    price_note: null,
    display_order: 4,
    status: 'available',
    is_featured: true,
    image_url: '/images/dacha-tv/products/swarm-lure-01.jpg',
    image_alt: 'Приманка для роїв Dacha TV',
    youtube_video_url: null,
    gallery_images: null,
  },
  {
    id: 'static-beekeeper-5',
    name: 'Вощина Dacha TV',
    slug: 'wax-foundation',
    product_type: 'apiary_supply',
    description: 'Натуральна бджолиновощина з якісного бджолиного воску. Підходить для стандартних рамок Дадан та інших типів вуликів.',
    full_description: null,
    breeds: null,
    season_note: null,
    price_uah: null,
    price_note: null,
    display_order: 5,
    status: 'available',
    is_featured: false,
    image_url: null,
    image_alt: 'Вощина Dacha TV',
    youtube_video_url: null,
    gallery_images: null,
  },
]

export const STATIC_BEEKEEPER_SLUGS = STATIC_BEEKEEPER.map((p) => p.slug)
